name: Build Android APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Installazione Dipendenze
        run: npm install

      - name: Sincronizzazione Capacitor
        run: npx cap sync android

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Compilazione APK
        working-directory: ./android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Salvataggio APK
        uses: actions/upload-artifact@v4
        with:
          name: Gens-Ssshhh-App
          path: android/app/build/outputs/apk/debug/app-debug.apk